# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift-Weibo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'QorumLogs'
  # Pods for Swift-Weibo

  target 'Swift-WeiboTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Swift-WeiboUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
